name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "36 1,13 * * *"
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: 
        github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: 签到
        run: |
          python3 -m pip install --upgrade pip
          pip install requests
          python3 main.py
